# spring.application.name=consumer

server:
  port: 8763

spring:
  application:
    name: eureka-consumer

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka # 指定服务注册中心

#Feign开启熔断器，在feignClient注解上新增fallback注解，值为具体处理类
